#!/usr/bin/env node
/**
 * Generates the project graph that agents read INSTEAD of opening source files.
 *
 *   docs/graph/symbols.json  every module's exported symbols with full type signatures + imports
 *   docs/graph/MAP.md        the readable version: module tree, exports, and who depends on what
 *
 * Output is sorted throughout so the committed copy has stable diffs and CI can detect staleness.
 */
import { Project, Node } from 'ts-morph';
import { writeFileSync, mkdirSync } from 'node:fs';
import { relative, resolve, dirname } from 'node:path';

const ROOT = resolve(process.argv[2] ?? '.');
const OUT = resolve(ROOT, 'docs/graph');
const rel = (p) => relative(ROOT, p).split('\\').join('/');

/**
 * Sort by UTF-16 code unit, never `localeCompare`. This file's output is a COMMITTED artifact that
 * CI regenerates and compares byte-for-byte, so the ordering must be identical on every machine.
 * Locale-aware collation is not: macOS treats `_` and `(` as ignorable punctuation and sorts
 * `app/_layout.tsx` first, while Linux CI sorts it last. That difference alone marked the graph
 * "stale" on every single pull request.
 */
const byText = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

const project = new Project({ tsConfigFilePath: resolve(ROOT, 'tsconfig.json') });
const files = project
  .getSourceFiles()
  .filter((f) => {
    const p = rel(f.getFilePath());
    return /^(app|src)\//.test(p) && !/\.(test|spec)\.tsx?$/.test(p) && !p.includes('/__');
  })
  .sort((a, b) => byText(rel(a.getFilePath()), rel(b.getFilePath())));

/** One-line, readable type for a symbol — this is what saves an agent from reading the file. */
function signatureOf(name, decl) {
  try {
    if (Node.isFunctionDeclaration(decl) || Node.isMethodDeclaration(decl)) {
      const params = decl.getParameters().map((p) => p.getText()).join(', ');
      const ret = decl.getReturnTypeNode()?.getText() ?? decl.getReturnType().getText(decl);
      return `function ${name}(${params}): ${ret}`;
    }
    if (Node.isClassDeclaration(decl)) return `class ${name}`;
    if (Node.isInterfaceDeclaration(decl)) return `interface ${name}`;
    if (Node.isTypeAliasDeclaration(decl)) return `type ${name} = ${decl.getTypeNode()?.getText() ?? '…'}`;
    if (Node.isEnumDeclaration(decl)) return `enum ${name}`;
    const t = decl.getType().getText(decl);
    return `const ${name}: ${t}`;
  } catch {
    return name;
  }
}

const modules = {};
const importedBy = {};

for (const f of files) {
  const path = rel(f.getFilePath());

  const exports = [];
  for (const [name, decls] of f.getExportedDeclarations()) {
    const decl = decls[0];
    if (!decl) continue;
    let sig = signatureOf(name, decl);
    if (sig.length > 400) sig = sig.slice(0, 397) + '...';
    exports.push(sig);
  }
  exports.sort(byText);

  /**
   * Project imports are recorded by path; everything else by its bare specifier ("react-native",
   * not the .d.ts the resolver happened to land on).
   *
   * That is both more useful — "this imports react-native" is the fact an agent wants — and the
   * only reproducible option. Resolved node_modules paths are machine-dependent: an agent worktree
   * symlinks node_modules to the main checkout, so they resolve to "../../node_modules/..." there
   * and "node_modules/..." in CI, which marked the committed graph stale on every run.
   */
  const imports = [];
  for (const d of f.getImportDeclarations()) {
    const target = d.getModuleSpecifierSourceFile();
    const targetPath = target ? rel(target.getFilePath()) : null;
    const isProjectFile = targetPath !== null && /^(app|src)\//.test(targetPath);

    imports.push(isProjectFile ? targetPath : d.getModuleSpecifierValue());
    if (isProjectFile) (importedBy[targetPath] ??= []).push(path);
  }

  modules[path] = {
    exports,
    imports: [...new Set(imports)].sort(byText),
    loc: f.getEndLineNumber(),
  };
}

for (const [k, v] of Object.entries(importedBy)) {
  if (modules[k]) modules[k].importedBy = [...new Set(v)].sort(byText);
}

mkdirSync(OUT, { recursive: true });

const symbols = {
  generated: 'scripts/graph-gen.mjs — do not edit by hand',
  moduleCount: Object.keys(modules).length,
  modules: Object.fromEntries(Object.entries(modules).sort(([a], [b]) => byText(a, b))),
};
writeFileSync(resolve(OUT, 'symbols.json'), JSON.stringify(symbols, null, 2) + '\n');

let md = `# Module map

Generated by \`scripts/graph.sh\` — do not edit by hand.

**Read this instead of opening source files.** For an exact signature:

\`\`\`bash
jq -r '.modules["src/db/queries/nutrition.ts"].exports[]' docs/graph/symbols.json
\`\`\`

${Object.keys(modules).length} modules.

`;

let group = '';
for (const [path, m] of Object.entries(symbols.modules)) {
  const dir = dirname(path);
  if (dir !== group) {
    group = dir;
    md += `\n## \`${dir}/\`\n`;
  }
  md += `\n### \`${path}\`  <sub>${m.loc} lines</sub>\n\n`;
  md += m.exports.length
    ? m.exports.map((e) => `- \`${e}\``).join('\n') + '\n'
    : '_no exports_\n';
  if (m.importedBy?.length) {
    md += `\n<sub>used by: ${m.importedBy.map((p) => `\`${p}\``).join(', ')}</sub>\n`;
  }
}
writeFileSync(resolve(OUT, 'MAP.md'), md);

console.log(`graph: ${Object.keys(modules).length} modules -> docs/graph/{symbols.json,MAP.md}`);
